#!/usr/bin/env python3
"""
topo.py - Quantum-Safe SDN Control-Plane Migration Orchestrator
Mininet emulated data plane. THIS IS THE ONLY FILE YOU EDIT TO CHANGE THE TOPOLOGY.

Everything else adapts on its own:
  * topology.py / coverage.py / optimizer / monitor : live LLDP discovery, no hardcoding
  * flows_config.json, docs/PORTS.md, port registry, Hybrid certs :
        regenerated by ../sync_topology.sh, which this script runs automatically
        after the switches are up (disable with QSMO_AUTO_SYNC=0)
  * live tests : size taken from the OVS bridge count (QSMO_EXPECTED_SWITCHES to override)

HOW TO CHANGE THE TOPOLOGY
--------------------------
Option 1 - edit the line  TOPOLOGY = default_three_tier()  below, e.g.
        TOPOLOGY = ring(6)            TOPOLOGY = tree(depth=3, fanout=2)
        TOPOLOGY = line(5)            TOPOLOGY = star(8)      TOPOLOGY = mesh(4)
Option 2 - no edit:   sudo python3 network/topo.py --topology ring:6
        (default | line:N | ring:N | star:N | mesh:N | tree:DEPTH:FANOUT)
Option 3 - write your own: return/define a dict with the three keys
        {"switches": {name: dpid}, "hosts": {host: switch}, "links": [(sw, sw), ...]}

Rules (validated before Mininet starts):
  * switch names are Mininet-style (s0, s1, ...), dpids are explicit, unique, NON-ZERO
    16-hex strings (OVS treats an all-zero dpid as unset and invents a random one)
  * the switch graph must be connected, hosts must attach to existing switches
  * if the switch graph has a loop, STP is enabled and we wait for it to converge;
    loop-free topologies skip STP and start in seconds

WHY SSL HERE, AND WHY IT'S "LEGACY" NOT "HYBRID" YET
------------------------------------------------------
Every switch's OpenFlow control channel is brought up over TLS using CLASSICAL
certificates (gen_certs.sh). That is the real "Legacy" state migrate_link.py
migrates OUT of. Real Hybrid TLS is added per link by migrate_link.py via stunnel.

IMPORTANT - run migration/gen_certs.sh BEFORE this script. It expects:
    migration/certs/ca.cert, switch.key, switch.cert  (shared by all switches)
"""

import argparse
import os
import subprocess
import sys
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
CERT_DIR = os.path.join(_HERE, '..', 'migration', 'certs')
CA_CERT = os.path.join(CERT_DIR, 'ca.cert')
SWITCH_KEY = os.path.join(CERT_DIR, 'switch.key')
SWITCH_CERT = os.path.join(CERT_DIR, 'switch.cert')
SYNC_SCRIPT = os.path.join(_HERE, '..', 'sync_topology.sh')

CONTROLLER_IP = '127.0.0.1'
CONTROLLER_PORT = 6653

STP_WAIT_S = int(os.environ.get('QSMO_STP_WAIT', '45'))


# ======================================================================
# Topology generators. Each returns {"switches", "hosts", "links"}.
# ======================================================================

def _dpid(i):
    return '%016x' % i


def default_three_tier():
    """The original 7-switch testbed: core s0, agg s1/s2 (cross-linked), 4 edge switches."""
    return {
        'switches': {
            's0': '0000000000000010',  # core (explicit non-zero; see rules above)
            's1': '0000000000000001',  # agg-A
            's2': '0000000000000002',  # agg-B
            's3': '0000000000000003',  # edge
            's4': '0000000000000004',  # edge
            's5': '0000000000000005',  # edge
            's6': '0000000000000006',  # edge
        },
        'hosts': {'h1': 's3', 'h2': 's3', 'h3': 's4', 'h4': 's4',
                  'h5': 's5', 'h6': 's5', 'h7': 's6', 'h8': 's6'},
        'links': [('s3', 's1'), ('s4', 's1'), ('s5', 's2'), ('s6', 's2'),
                  ('s1', 's0'), ('s2', 's0'), ('s1', 's2')],
    }


def _attach_hosts(switch_names, hosts_per_switch, hosts=None):
    hosts = {} if hosts is None else hosts
    for sw in switch_names:
        for _ in range(hosts_per_switch):
            hosts['h%d' % (len(hosts) + 1)] = sw
    return hosts


def _named(n):
    names = ['s%d' % i for i in range(n)]
    return names, {nm: _dpid(i + 1) for i, nm in enumerate(names)}


def line(n, hosts_per_switch=1):
    names, sw = _named(n)
    return {'switches': sw, 'hosts': _attach_hosts(names, hosts_per_switch),
            'links': [(names[i], names[i + 1]) for i in range(n - 1)]}


def ring(n, hosts_per_switch=1):
    names, sw = _named(n)
    links = [(names[i], names[i + 1]) for i in range(n - 1)]
    if n > 2:
        links.append((names[-1], names[0]))
    return {'switches': sw, 'hosts': _attach_hosts(names, hosts_per_switch), 'links': links}


def star(n, hosts_per_leaf=1):
    """Hub s0 plus n leaf switches (n+1 switches total)."""
    names, sw = _named(n + 1)
    return {'switches': sw, 'hosts': _attach_hosts(names[1:], hosts_per_leaf),
            'links': [(names[0], nm) for nm in names[1:]]}


def mesh(n, hosts_per_switch=1):
    names, sw = _named(n)
    return {'switches': sw, 'hosts': _attach_hosts(names, hosts_per_switch),
            'links': [(names[i], names[j]) for i in range(n) for j in range(i + 1, n)]}


def tree(depth, fanout, hosts_per_leaf=1):
    """Complete tree: depth levels below the root, `fanout` children each."""
    links, level, count = [], [0], 1
    for _ in range(depth):
        nxt = []
        for parent in level:
            for _ in range(fanout):
                links.append(('s%d' % parent, 's%d' % count))
                nxt.append(count)
                count += 1
        level = nxt
    names, sw = _named(count)
    return {'switches': sw, 'hosts': _attach_hosts(['s%d' % i for i in level], hosts_per_leaf),
            'links': links}


def from_name(spec):
    """'ring:6' / 'tree:3:2' / 'default' -> topology dict."""
    kind, *args = spec.strip().lower().split(':')
    nums = [int(a) for a in args]
    makers = {'default': default_three_tier, 'line': line, 'ring': ring,
              'star': star, 'mesh': mesh, 'tree': tree}
    if kind not in makers:
        raise SystemExit("unknown topology %r (use default|line:N|ring:N|star:N|mesh:N|tree:D:F)" % spec)
    return makers[kind](*nums)


# ======================================================================
#                      >>>  EDIT THIS LINE  <<<
# ======================================================================
TOPOLOGY = default_three_tier()
# ======================================================================


# ----------------------------------------------------------------------
# Validation / planning (pure Python - no Mininet needed)
# ----------------------------------------------------------------------

def plan_topology(spec):
    """Validate `spec`; return a dict with the normalized plan plus 'cyclic'."""
    sw, hosts, links = spec['switches'], spec['hosts'], [tuple(l) for l in spec['links']]
    if len(sw) < 2:
        raise ValueError('need at least 2 switches')
    seen = {}
    for name, dpid in sw.items():
        d = str(dpid).lower()
        if len(d) != 16 or any(c not in '0123456789abcdef' for c in d):
            raise ValueError('%s: dpid %r must be 16 hex chars' % (name, dpid))
        if int(d, 16) == 0:
            raise ValueError('%s: dpid must be non-zero (OVS treats all-zero as unset)' % name)
        if d in seen:
            raise ValueError('dpid %s used by both %s and %s' % (d, seen[d], name))
        seen[d] = name
    for h, s in hosts.items():
        if s not in sw:
            raise ValueError('host %s attached to unknown switch %s' % (h, s))
    norm = set()
    for a, b in links:
        if a not in sw or b not in sw:
            raise ValueError('link (%s, %s) references an unknown switch' % (a, b))
        if a == b:
            raise ValueError('self-link on %s' % a)
        key = frozenset((a, b))
        if key in norm:
            raise ValueError('duplicate link (%s, %s)' % (a, b))
        norm.add(key)
    # connectivity via union-find
    parent = {n: n for n in sw}

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x
    for a, b in links:
        parent[find(a)] = find(b)
    if len({find(n) for n in sw}) != 1:
        raise ValueError('switch graph is not connected')
    return {'switches': dict(sw), 'hosts': dict(hosts), 'links': links,
            'cyclic': len(links) > len(sw) - 1}


def host_ip(index, total):
    """h1 -> 10.0.0.11/24 (original scheme); switches to a /16 when there are many hosts."""
    n = index + 10
    if total + 10 < 250:
        return '10.0.0.%d/24' % n
    return '10.0.%d.%d/16' % (n // 250, n % 250 + 1)


# ----------------------------------------------------------------------
# Mininet side
# ----------------------------------------------------------------------

def enable_stp(switch):
    """Force STP on via ovs-vsctl (the stp=True kwarg is not reliable on all builds)."""
    switch.cmd(f'ovs-vsctl set bridge {switch.name} stp_enable=true')


def configure_switch_ssl(switch):
    """Point one switch's OpenFlow control channel at the controller over SSL."""
    switch.cmd(f'ovs-vsctl set-ssl {SWITCH_KEY} {SWITCH_CERT} {CA_CERT}')
    switch.cmd(
        f'ovs-vsctl set-controller {switch.name} '
        f'ssl:{CONTROLLER_IP}:{CONTROLLER_PORT}'
    )


def run_sync():
    """Regenerate flows_config.json, docs/PORTS.md, port registry and Hybrid certs."""
    from mininet.log import info, warn
    if os.environ.get('QSMO_AUTO_SYNC', '1') == '0':
        info('*** QSMO_AUTO_SYNC=0 -> skipping sync_topology.sh (run it by hand)\n')
        return
    info('*** Syncing flows / ports / Hybrid certs to this topology (sync_topology.sh)\n')
    try:
        subprocess.run(['bash', SYNC_SCRIPT], check=True, timeout=600)
    except Exception as exc:  # never block the testbed on a sync problem
        warn('*** sync_topology.sh failed (%s). Run it manually before migrating.\n' % exc)


def build(spec=None):
    from mininet.net import Mininet
    from mininet.node import RemoteController, OVSKernelSwitch
    from mininet.cli import CLI
    from mininet.link import TCLink
    from mininet.log import info

    plan = plan_topology(spec or TOPOLOGY)
    cyclic = plan['cyclic']
    names = list(plan['switches'])

    net = Mininet(controller=RemoteController, switch=OVSKernelSwitch,
                  link=TCLink, autoSetMacs=True)

    info('*** Adding controller (external os-ken process, SSL, started separately)\n')
    net.addController('c0', controller=RemoteController,
                      ip=CONTROLLER_IP, port=CONTROLLER_PORT)

    info('*** Adding %d switches (STP %s)\n' % (len(names), 'ON - topology has a loop' if cyclic else 'off - loop-free'))
    switches = {}
    for name, dpid in plan['switches'].items():
        switches[name] = net.addSwitch(name, cls=OVSKernelSwitch, protocols='OpenFlow13',
                                       stp=cyclic, dpid=dpid)

    info('*** Adding %d hosts\n' % len(plan['hosts']))
    total = len(plan['hosts'])
    hosts = {}
    for i, h in enumerate(plan['hosts'], start=1):
        hosts[h] = net.addHost(h, ip=host_ip(i, total))

    info('*** Wiring hosts to switches\n')
    for h, s in plan['hosts'].items():
        net.addLink(hosts[h], switches[s])

    info('*** Wiring %d switch-to-switch links\n' % len(plan['links']))
    for a, b in plan['links']:
        net.addLink(switches[a], switches[b])

    info('*** Starting network\n')
    net.start()

    if cyclic:
        info('*** Force-enabling STP via ovs-vsctl\n')
        for name in names:
            enable_stp(switches[name])

    # Flip every switch to ssl: immediately, before any waiting, to keep the
    # window where switches retry plaintext against an SSL listener short.
    info('*** Configuring per-switch SSL control channel (%d switches)\n' % len(names))
    for name in names:
        configure_switch_ssl(switches[name])

    run_sync()

    if cyclic:
        info('*** Waiting for STP to converge (%ds)...\n' % STP_WAIT_S)
        time.sleep(STP_WAIT_S)
        info('*** Verify: sudo ovs-appctl stp/show <switch>  (ports forwarding, not blocking)\n')
    else:
        time.sleep(3)
    info('*** Verify with: sudo ovs-vsctl show   (is_connected: true on Controller lines)\n')
    info('*** Ready. Try: pingall\n')
    CLI(net)
    net.stop()


def main(argv=None):
    ap = argparse.ArgumentParser(description='Launch the QSMO Mininet testbed.')
    ap.add_argument('--topology', help='default | line:N | ring:N | star:N | mesh:N | tree:DEPTH:FANOUT')
    ap.add_argument('--check', action='store_true', help='validate the topology and exit (no Mininet)')
    args = ap.parse_args(argv)
    spec = from_name(args.topology) if args.topology else TOPOLOGY
    plan = plan_topology(spec)
    print('Topology: %d switches, %d hosts, %d links, %s' % (
        len(plan['switches']), len(plan['hosts']), len(plan['links']),
        'has loop (STP on)' if plan['cyclic'] else 'loop-free (STP off)'))
    if args.check:
        return
    from mininet.log import setLogLevel
    setLogLevel('info')
    build(spec)


if __name__ == '__main__':
    main()
