#!/usr/bin/env python3
"""
topo.py - Quantum-Safe SDN Control-Plane Migration Orchestrator
Mininet emulated data plane (3-tier tree + redundant cross-link),
with each switch's OpenFlow control channel brought up over SSL/TLS
against a real certificate chain instead of plaintext TCP.

                          +-------- s0 (core) --------+
                          |                            |
                    s1 (agg-A) ------cross-link------ s2 (agg-B)
                    /       \                        /       \
              s3(edge)   s4(edge)              s5(edge)   s6(edge)
               /  \        /  \                  /  \       /  \
             h1   h2     h3   h4               h5   h6    h7   h8

Flow groups (must match flows_config.json used by topology.py/coverage.py):
  h1, h2  -> "hospital" (edge s3)
  h3, h4  -> "banking"  (edge s4)
  h5, h6  -> "video"    (edge s5)
  h7, h8  -> "iot"      (edge s6)

WHY SSL HERE, AND WHY IT'S "LEGACY" NOT "HYBRID" YET
------------------------------------------------------
This script brings every switch's OpenFlow control channel up over TLS
using CLASSICAL certificates (ECDSA/RSA), generated by gen_certs.sh.
That's the real, working "Legacy" state Feature 4 (migrate_link.py)
starts from and migrates OUT of.

It is NOT expected to carry Hybrid PQC groups (x25519_mlkem768) on its
own: Open vSwitch's SSL support links against the system libssl (via
apt), not the oqs-provider-enabled /opt/openssl35 build from the
environment setup guide's Step 6/8. Getting real Hybrid TLS onto this
control channel is Feature 4's job, via a per-link stunnel proxy (see
the bring-up guide) -- this script's job is only to establish the
REAL classical baseline and the certificate trust chain that stunnel
will reuse, so "Legacy state" in the security graph corresponds to an
actual working SSL connection, not a simulated placeholder.

IMPORTANT - run gen_certs.sh BEFORE this script. It expects:
    ~/sdn-project/certs/ca.cert
    ~/sdn-project/certs/controller.key / controller.cert
    ~/sdn-project/certs/switch.key    / switch.cert   (shared by all switches --
        fine for a lab testbed; see gen_certs.sh's comments for the
        per-switch-cert alternative if you want closer-to-production realism)

IMPORTANT - STP convergence: after net.start(), give the network ~30-45
seconds before running pingall so STP can finish electing the blocked
port on the s1-s2-s0 triangle.
"""

import os
import time

from mininet.net import Mininet
from mininet.node import RemoteController, OVSKernelSwitch
from mininet.cli import CLI
from mininet.link import TCLink
from mininet.log import setLogLevel, info

CERT_DIR = os.path.join(os.path.dirname(__file__), '..', 'migration', 'certs')
CA_CERT = os.path.join(CERT_DIR, 'ca.cert')
SWITCH_KEY = os.path.join(CERT_DIR, 'switch.key')
SWITCH_CERT = os.path.join(CERT_DIR, 'switch.cert')

CONTROLLER_IP = '127.0.0.1'
CONTROLLER_PORT = 6653

# All 7 switches. c0 is NOT a Mininet node here -- the controller is an
# external os-ken process on the VM's root namespace (see the bring-up
# guide). This list is only used to loop the post-start SSL config over
# every switch below.
ALL_SWITCHES = ['s0', 's1', 's2', 's3', 's4', 's5', 's6']


def enable_stp(switch):
    """
    Force STP on explicitly via ovs-vsctl. The stp=True kwarg passed to
    addSwitch() is not reliable on all Mininet/OVS version combinations
    -- if `ovs-appctl stp/show <switch>` reports "no such stp object"
    after net.start(), the kwarg silently didn't take effect and the
    s0-s1-s2 triangle is an unguarded L2 loop (broadcast storm on
    pingall). This is the defensive, always-works fallback.
    """
    switch.cmd(f'ovs-vsctl set bridge {switch.name} stp_enable=true')


def configure_switch_ssl(switch):
    """
    Point one switch's OpenFlow control channel at the controller over
    SSL, using the certs gen_certs.sh produced. Mininet's default
    net.addController()/controller= wiring only sets up plain TCP, so
    this runs the equivalent ovs-vsctl commands by hand after the
    switch is already up.
    """
    switch.cmd(f'ovs-vsctl set-ssl {SWITCH_KEY} {SWITCH_CERT} {CA_CERT}')
    switch.cmd(
        f'ovs-vsctl set-controller {switch.name} '
        f'ssl:{CONTROLLER_IP}:{CONTROLLER_PORT}'
    )


def build():
    net = Mininet(controller=RemoteController, switch=OVSKernelSwitch,
                  link=TCLink, autoSetMacs=True)

    info('*** Adding controller (external os-ken process, SSL, started separately)\n')
    # Registered with Mininet so switches know where to point -- but the
    # SSL target string is what actually matters; see configure_switch_ssl.
    net.addController('c0', controller=RemoteController,
                       ip=CONTROLLER_IP, port=CONTROLLER_PORT)

    info('*** Adding switches (core / aggregation / edge) with STP enabled\n')
    s0 = net.addSwitch('s0', cls=OVSKernelSwitch, protocols='OpenFlow13', stp=True)  # core
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch, protocols='OpenFlow13', stp=True)  # agg-A
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch, protocols='OpenFlow13', stp=True)  # agg-B
    s3 = net.addSwitch('s3', cls=OVSKernelSwitch, protocols='OpenFlow13', stp=True)  # edge - hospital
    s4 = net.addSwitch('s4', cls=OVSKernelSwitch, protocols='OpenFlow13', stp=True)  # edge - banking
    s5 = net.addSwitch('s5', cls=OVSKernelSwitch, protocols='OpenFlow13', stp=True)  # edge - video
    s6 = net.addSwitch('s6', cls=OVSKernelSwitch, protocols='OpenFlow13', stp=True)  # edge - iot
    switches = {'s0': s0, 's1': s1, 's2': s2, 's3': s3, 's4': s4, 's5': s5, 's6': s6}

    info('*** Adding hosts (flat 10.0.0.0/24 subnet)\n')
    h1 = net.addHost('h1', ip='10.0.0.11/24')  # hospital
    h2 = net.addHost('h2', ip='10.0.0.12/24')  # hospital
    h3 = net.addHost('h3', ip='10.0.0.13/24')  # banking
    h4 = net.addHost('h4', ip='10.0.0.14/24')  # banking
    h5 = net.addHost('h5', ip='10.0.0.15/24')  # video
    h6 = net.addHost('h6', ip='10.0.0.16/24')  # video
    h7 = net.addHost('h7', ip='10.0.0.17/24')  # iot
    h8 = net.addHost('h8', ip='10.0.0.18/24')  # iot

    info('*** Wiring hosts to edge switches\n')
    net.addLink(h1, s3); net.addLink(h2, s3)
    net.addLink(h3, s4); net.addLink(h4, s4)
    net.addLink(h5, s5); net.addLink(h6, s5)
    net.addLink(h7, s6); net.addLink(h8, s6)

    info('*** Wiring edge switches to aggregation switches\n')
    net.addLink(s3, s1); net.addLink(s4, s1)   # agg-A: hospital + banking
    net.addLink(s5, s2); net.addLink(s6, s2)   # agg-B: video + iot

    info('*** Wiring aggregation switches to the core switch\n')
    net.addLink(s1, s0); net.addLink(s2, s0)

    info('*** Adding the redundant agg-to-agg cross-link (creates the triangle)\n')
    net.addLink(s1, s2)

    info('*** Starting network\n')
    net.start()

    info('*** Force-enabling STP via ovs-vsctl (stp=True kwarg is not reliable on all builds)\n')
    for name in ALL_SWITCHES:
        enable_stp(switches[name])

    # Mininet's net.start() auto-configures each switch with a plain
    # "tcp:" controller target the instant the bridge comes up. If the
    # controller is SSL-only (as ours is), switches will spend this
    # window retrying plaintext against an SSL listener and the
    # controller will log WRONG_VERSION_NUMBER errors. Flip every
    # switch to "ssl:" immediately -- before the STP wait, not after --
    # to minimize that window instead of leaving it open for 45s.
    info('*** Configuring per-switch SSL control channel (all %d switches)\n' % len(ALL_SWITCHES))
    for name in ALL_SWITCHES:
        configure_switch_ssl(switches[name])

    info('*** Waiting for STP to converge (about 30-45s)...\n')
    time.sleep(45)

    info('*** Verify STP actually converged: sudo ovs-appctl stp/show s1   (ports should show forwarding, not blocking/listening)\n')
    info('*** Verify with: sudo ovs-vsctl show   (look for "is_connected: true" on Controller lines)\n')
    info('*** Ready. Try: pingall\n')
    CLI(net)
    net.stop()


if __name__ == '__main__':
    setLogLevel('info')
    build()